# Generated by Django 6.0.1 on 2026-01-26 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('template_type', models.CharField(choices=[('projects', 'По проектам'), ('tasks', 'По задачам'), ('employees', 'По сотрудникам'), ('financial', 'Финансовый'), ('deadlines', 'По срокам'), ('weekly', 'Еженедельный')], max_length=20, verbose_name='Тип отчета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('fields_config', models.JSONField(default=dict, verbose_name='Конфигурация полей')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование отчета')),
                ('report_type', models.CharField(choices=[('projects', 'По проектам'), ('tasks', 'По задачам'), ('employees', 'По сотрудникам'), ('clients', 'По клиентам'), ('financial', 'Финансовый')], max_length=20, verbose_name='Тип отчета')),
                ('start_date', models.DateField(verbose_name='Период с')),
                ('end_date', models.DateField(verbose_name='Период по')),
                ('status_filter', models.CharField(blank=True, max_length=50, verbose_name='Фильтр по статусу')),
                ('include_financial', models.BooleanField(default=False, verbose_name='Финансовые показатели')),
                ('include_deadlines', models.BooleanField(default=True, verbose_name='Сроки выполнения')),
                ('include_workload', models.BooleanField(default=True, verbose_name='Загрузка сотрудников')),
                ('include_risks', models.BooleanField(default=False, verbose_name='Риски и проблемы')),
                ('include_task_details', models.BooleanField(default=True, verbose_name='Детали по задачам')),
                ('include_files', models.BooleanField(default=False, verbose_name='Файлы приложений')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='Формат экспорта')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Файл отчета')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата формирования')),
                ('generation_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Время генерации (сек)')),
                ('is_success', models.BooleanField(default=True, verbose_name='Успешно сформирован')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сформировал')),
                ('projects', models.ManyToManyField(blank=True, to='projects.project', verbose_name='Проекты')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сформированный отчет',
                'verbose_name_plural': 'Сформированные отчеты',
                'ordering': ['-generated_at'],
            },
        ),
    ]
