# Generated by Django 6.0.1 on 2026-01-28 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'ordering': ['is_default', 'name'], 'verbose_name': 'Шаблон отчета', 'verbose_name_plural': 'Шаблоны отчетов'},
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='include_deadlines',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='include_files',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='include_financial',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='include_risks',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='include_task_details',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='include_workload',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='status_filter',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='template',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='fields_config',
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employee_reports', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='default_parameters',
            field=models.JSONField(default=dict, verbose_name='Параметры по умолчанию'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Ежедневный'), ('weekly', 'Еженедельный'), ('monthly', 'Ежемесячный'), ('quarterly', 'Ежеквартальный'), ('yearly', 'Ежегодный'), ('manual', 'По запросу')], default='manual', max_length=20, verbose_name='Частота формирования'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='include_columns',
            field=models.JSONField(default=list, verbose_name='Включаемые столбцы'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Шаблон по умолчанию'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='show_footer',
            field=models.BooleanField(default=True, verbose_name='Показывать подвал'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='show_header',
            field=models.BooleanField(default=True, verbose_name='Показывать заголовок'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='show_totals',
            field=models.BooleanField(default=True, verbose_name='Показывать итоги'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='export_format',
            field=models.CharField(choices=[('pdf', 'PDF')], default='pdf', max_length=10, verbose_name='Формат экспорта'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время формирования'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Сформировал'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='report_type',
            field=models.CharField(choices=[('projects', 'По проектам'), ('tasks', 'По задачам'), ('employees', 'По загрузке сотрудников'), ('tasks_period', 'Отчет по выполнению задач за период'), ('summary', 'Сводный отчет по деятельности агентства')], max_length=20, verbose_name='Тип отчета'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='template_type',
            field=models.CharField(choices=[('projects', 'По проектам'), ('tasks', 'По задачам'), ('employees', 'По загрузке сотрудников'), ('tasks_period', 'Отчет по выполнению задач за период'), ('summary', 'Сводный отчет по деятельности агентства')], max_length=20, verbose_name='Тип отчета'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['report_type', 'generated_at'], name='reports_gen_report__7f8afa_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['is_archived', 'is_active'], name='reports_gen_is_arch_039d9f_idx'),
        ),
    ]
