# Generated by Django 6.0.1 on 2026-01-26 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_system', models.BooleanField(default=True, verbose_name='В системе')),
                ('enable_email', models.BooleanField(default=True, verbose_name='По email')),
                ('enable_sms', models.BooleanField(default=False, verbose_name='SMS')),
                ('enable_telegram', models.BooleanField(default=False, verbose_name='Telegram')),
                ('notify_new_tasks', models.BooleanField(default=True, verbose_name='Новые задачи')),
                ('notify_deadlines', models.BooleanField(default=True, verbose_name='Просроченные сроки')),
                ('notify_project_changes', models.BooleanField(default=True, verbose_name='Изменения проектов')),
                ('notify_file_uploads', models.BooleanField(default=True, verbose_name='Загрузка файлов')),
                ('notify_comments', models.BooleanField(default=True, verbose_name='Комментарии')),
                ('work_hours_start', models.TimeField(default='09:00', verbose_name='Начало рабочих часов')),
                ('work_hours_end', models.TimeField(default='18:00', verbose_name='Конец рабочих часов')),
                ('quiet_hours_start', models.TimeField(default='22:00', verbose_name='Начало тихих часов')),
                ('quiet_hours_end', models.TimeField(default='08:00', verbose_name='Конец тихих часов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройка уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Новая задача'), ('task_deadline', 'Просроченная задача'), ('project_status', 'Изменение статуса проекта'), ('file_uploaded', 'Загружен новый файл'), ('comment_added', 'Добавлен комментарий'), ('report_ready', 'Отчет сформирован'), ('system', 'Системное уведомление')], max_length=20, verbose_name='Тип уведомления')),
                ('channel', models.CharField(choices=[('system', 'В системе'), ('email', 'Email'), ('sms', 'SMS'), ('telegram', 'Telegram')], default='system', max_length=10, verbose_name='Канал отправки')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['scheduled_for'], name='notificatio_schedul_cf7340_idx')],
            },
        ),
    ]
