# Generated by Django 6.0.1 on 2026-01-26 11:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Название проекта содержит недопустимые символы', regex='^[а-яёА-ЯЁa-zA-Z0-9\\s\\-,\\\\.()]{3,255}$'), django.core.validators.MinLengthValidator(3)], verbose_name='Название проекта')),
                ('description', models.TextField(validators=[django.core.validators.RegexValidator(message='Описание содержит недопустимые символы', regex='^[а-яёА-ЯЁa-zA-Z0-9\\s\\-,\\\\.():;!?"\\\'«»]*$')], verbose_name='Описание проекта')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('planned_end_date', models.DateField(verbose_name='Плановая дата завершения')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата завершения')),
                ('status', models.CharField(choices=[('planned', 'Планируется'), ('in_work', 'В работе'), ('on_approval', 'На согласовании'), ('completed', 'Завершён'), ('paused', 'Приостановлен')], default='planned', max_length=20, verbose_name='Статус проекта')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20, verbose_name='Приоритет проекта')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Бюджет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Менеджер'), ('designer', 'Дизайнер'), ('developer', 'Разработчик'), ('copywriter', 'Копирайтер'), ('qa', 'Тестировщик')], max_length=20, verbose_name='Роль в проекте')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Сотрудник')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проекта',
                'unique_together': {('project', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Название задачи содержит недопустимые символы', regex='^[а-яёА-ЯЁa-zA-Z0-9\\s\\-,\\\\.()]{3,255}$'), django.core.validators.MinLengthValidator(3)], verbose_name='Название задачи')),
                ('description', models.TextField(validators=[django.core.validators.RegexValidator(message='Описание содержит недопустимые символы', regex='^[а-яёА-ЯЁa-zA-Z0-9\\s\\-,\\\\.():;!?"\\\'«»]*$')], verbose_name='Описание задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата постановки')),
                ('deadline', models.DateField(verbose_name='Срок выполнения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата выполнения')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('in_work', 'В работе'), ('on_review', 'На проверке'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='created', max_length=20, verbose_name='Статус задачи')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20, verbose_name='Приоритет задачи')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент выполнения')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Оценка времени (ч)')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Фактическое время (ч)')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['priority', 'deadline'],
                'indexes': [models.Index(fields=['status'], name='projects_ta_status_d6b74c_idx'), models.Index(fields=['deadline'], name='projects_ta_deadlin_abbe13_idx'), models.Index(fields=['priority'], name='projects_ta_priorit_dd6c2d_idx')],
            },
        ),
    ]
