# Generated by Django 6.0.1 on 2026-01-28 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Описание содержит недопустимые символы', regex='^[а-яёА-ЯЁa-zA-Z0-9\\s\\-,\\\\.():;!?"\\\'«»]*$')], verbose_name='Описание проекта'),
        ),
    ]
