# Generated by Django 6.0.1 on 2026-01-26 11:47

import django.core.validators
import django.db.models.deletion
import files.models.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('brief', 'Брифы и ТЗ'), ('sketch', 'Эскизы и концепции'), ('final', 'Финальные материалы'), ('reference', 'Референсы'), ('document', 'Документация'), ('other', 'Прочие')], max_length=50, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория файлов',
                'verbose_name_plural': 'Категории файлов',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Название файла содержит недопустимые символы', regex='^[а-яёА-ЯЁa-zA-Z0-9\\s\\-,\\\\.()_]{1,255}$')], verbose_name='Название файла')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file', models.FileField(upload_to=files.models.utils.file_upload_path, verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('document', 'Документ'), ('archive', 'Архив'), ('video', 'Видео'), ('audio', 'Аудио'), ('other', 'Другое')], max_length=20, verbose_name='Тип файла')),
                ('extension', models.CharField(choices=[('.jpg', 'JPG'), ('.jpeg', 'JPEG'), ('.png', 'PNG'), ('.gif', 'GIF'), ('.pdf', 'PDF'), ('.doc', 'DOC'), ('.docx', 'DOCX'), ('.xls', 'XLS'), ('.xlsx', 'XLSX'), ('.ppt', 'PPT'), ('.pptx', 'PPTX'), ('.psd', 'PSD'), ('.ai', 'AI'), ('.indd', 'INDD'), ('.mp4', 'MP4'), ('.mov', 'MOV'), ('.avi', 'AVI'), ('.zip', 'ZIP'), ('.rar', 'RAR')], max_length=10, verbose_name='Расширение')),
                ('size', models.BigIntegerField(verbose_name='Размер файла (байт)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('version', models.IntegerField(default=1, verbose_name='Версия')),
                ('is_current', models.BooleanField(default=True, verbose_name='Текущая версия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.filecategory', verbose_name='Категория')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.task', verbose_name='Задача')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл проекта',
                'verbose_name_plural': 'Файлы проектов',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileVersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='Версия')),
                ('file', models.FileField(upload_to=files.models.utils.file_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('changes_description', models.TextField(blank=True, verbose_name='Описание изменений')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.projectfile')),
            ],
            options={
                'verbose_name': 'История версий файла',
                'verbose_name_plural': 'История версий файлов',
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['project', 'task'], name='files_proje_project_53dc25_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['file_type'], name='files_proje_file_ty_0f6fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['uploaded_at'], name='files_proje_uploade_18a772_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fileversionhistory',
            unique_together={('project_file', 'version')},
        ),
    ]
