# Generated by Django 6.0.1 on 2026-01-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='fileversionhistory',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='Хеш файла'),
        ),
        migrations.AddField(
            model_name='fileversionhistory',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)'),
        ),
    ]
