# Generated by Django 6.0.1 on 2026-01-26 11:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Название компании содержит недопустимые символы', regex='^[а-яёА-ЯЁa-zA-Z0-9\\s\\-,"«».]{2,255}$'), django.core.validators.MinLengthValidator(2)], verbose_name='Название компании/ФИО')),
                ('contact_person', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='ФИО содержит недопустимые символы', regex='^[а-яёА-ЯЁ\\s\\.\\-]{2,150}$')], verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Введите корректный email', regex='^[a-zA-Z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$')], verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('director', 'Руководитель'), ('manager', 'Менеджер проекта'), ('designer', 'Дизайнер'), ('copywriter', 'Копирайтер')], default='designer', max_length=20, verbose_name='Роль')),
                ('account_status', models.CharField(choices=[('active', 'Активна'), ('blocked', 'Заблокирована')], default='active', max_length=20, verbose_name='Статус учетной записи')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс')),
                ('language', models.CharField(default='ru', max_length=10, verbose_name='Язык интерфейса')),
                ('theme', models.CharField(default='light', max_length=20, verbose_name='Тема интерфейса')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='Двухфакторная аутентификация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('work_phone', models.CharField(blank=True, max_length=20, verbose_name='Рабочий телефон')),
                ('work_email', models.EmailField(max_length=254, verbose_name='Рабочая почта')),
                ('employment_status', models.CharField(choices=[('active', 'Активен'), ('fired', 'Уволен'), ('vacation', 'В отпуске')], default='active', max_length=20, verbose_name='Статус занятости')),
                ('hire_date', models.DateField(verbose_name='Дата приема')),
                ('salary_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ставка оплаты')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
